<?php

$examples_scripts=array(
    'hello_world'=>array(
        "title"=>'Bonjour le monde !',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
            "css"=>"ressources/common/assets/examples/css/empty.css",
            "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
        "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/hello_world.consignes.html",
        "activeEditor"=>"javascript",
        "editors"=>array(
            "javascript"=>true,
            "css"=>false,
            "html"=>false)
        ),
    'variable_1'=>array(
        "title"=>'Une variable',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
            "css"=>"ressources/common/assets/examples/css/empty.css",
            "javascript"=>"ressources/javascript_base/assets/examples/javascript/variable_1.js"
        ),
        "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/variable_1.consignes.html",
        "activeEditor"=>"javascript",
        "editors"=>array(
            "javascript"=>true,
            "css"=>false,
            "html"=>false)
        ),
    'variable_2'=>array(
        "title"=>'Une variable ?',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/variable_1.js"
        ),
        "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/variable_2.consignes.html",
        "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'variable_3'=>array(
        "title"=>'Une variable ?',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
        "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/variable_3.consignes.html",
        "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'operations_1'=>array(
        "title"=>'Ajouter deux variables',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/operations_1.js"
        ),
        "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/operations_1.consignes.html",
        "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'operations_2'=>array(
        "title"=>'Incrémentation',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
            "css"=>"ressources/common/assets/examples/css/empty.css",
            "javascript"=>"ressources/javascript_base/assets/examples/javascript/operations_2.js"
        ),
        "activeEditor"=>"javascript",
        "editors"=>array(
            "javascript"=>true,
            "css"=>false,
            "html"=>false)
        ),
    'string'=>array(
        "title"=>'Les chaines de caractères',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/string.js"
        ),
        "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'typeof'=>array(
        "title"=>'Typage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/typeof.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'undefined'=>array(
        "title"=>'Undefined ! ',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/undefined.consignes.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'concatenation'=>array(
        "title"=>'Concatenation ',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/concatenation.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'transtypage'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/transtypage.consignes.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'prompt'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/prompt.consignes.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'promptNb'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/promptNb.consignes.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'boolean_1'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/boolean_1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'boolean_2'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/boolean_2.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'boolean_3'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/boolean_3.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'boolean_4'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/boolean_4.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'boolean_5'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/boolean_5.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'boolean_6'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/boolean_6.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'boolean_7'=>array(
        "title"=>'Transtypage',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/boolean_7.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'condition_1'=>array(
        "title"=>'Branchement conditionnel : if/else',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/condition_1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'condition_2'=>array(
        "title"=>'Branchement conditionnel : if/else',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/condition_2.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'while_1'=>array(
        "title"=>'Boucle while : de 1 à 10',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/while_1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'while_2'=>array(
        "title"=>'Boucle while : tables de multiplication',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/while_2.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'while_3'=>array(
        "title"=>'Reposer la question',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/while_3.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'for_1'=>array(
        "title"=>'Boucle for ',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/for_1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'for_2'=>array(
        "title"=>'Encore les tables !',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/for_2.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'fonction_1'=>array(
        "title"=>'Fonction simple',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/fonction_1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'fonction_2'=>array(
        "title"=>'Fonction avec deux paramètres',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/fonction_2.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'fonction_3'=>array(
        "title"=>'Fonctions avec paramètres variés',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/fonction_3.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'fonction_4'=>array(
        "title"=>'Fonction sans return',
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/fonction_4.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_a1'=>array(
        "title"=>"Accéder au contenu d'un tableau",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_a1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_a2'=>array(
        "title"=>"Les mois de l'année",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/common/assets/examples/javascript/empty.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/array_a2.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_b1'=>array(
        "title"=>"La longueur du tableau",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_b1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_b2'=>array(
        "title"=>"Push !",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_b2.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/array_b2.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_b3'=>array(
        "title"=>"Pop !",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_b3.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_b4'=>array(
        "title"=>"Over the rainbow",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_b4.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/array_b4.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_c1'=>array(
        "title"=>"Five days a week ?",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_c1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_c2'=>array(
        "title"=>"For each day",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_c2.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'array_c3'=>array(
        "title"=>"Les nombres premiers",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/array_c3.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'portee_1'=>array(
        "title"=>"Inconnue au bataillon?",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/portee_1.js"
        ),
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
    'portee_2'=>array(
        "title"=>"Tu me vois, tu me vois plus !",
        "files"=>array(
            "html"=>"ressources/common/assets/examples/html/default.html",
        "css"=>"ressources/common/assets/examples/css/empty.css",
        "javascript"=>"ressources/javascript_base/assets/examples/javascript/portee_2.js"
        ),
      "fichierConsignes"=>"ressources/javascript_base/assets/examples/html/portee_2.consigne.html",
      "activeEditor"=>"javascript",
        "editors"=>array("javascript"=>true,
        "css"=>false,
        "html"=>false)),
);
